Backend/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/

// Rutas GENERADAS por auth:register,login
Auth::routes();

/**
 *                          BASICO!!
 *      VISTAS : /resources/views/....      Ejm: home.blade.php
 *      CONTROLADORES : /app/Http/Controlollers/....    Ejm: HomeController.php
 *      MODELOS : /app/....       Ejm: User.php
 *      RUTAS : /routes/web.php
 */

// '/' - es la ruta que se vera como pagina inicial
// 'HomeController@index' - HomeController es el CONTROLADOR que utiliza
// 'HomeController@index' - index es el FUNCION dentro del controlador Homecontroller, 
//                          esta funcion es la que manda la 'vista' inicial
//  'home' - para asignar toda esta vista a esa variable
//      ejm 1: 
//           Route::get('/', 'ClienteController@lista')->name('cliente.lista');
//      ejm 2: ->name('NOMBRE_DE_CONTROLADOR.FUNCION_QUE_REALIZA')
Route::get('/', 'HomeController@index')->name('home');
Route::get('/inmuebles/buscar','InmueblesController@buscador');
Route::post('/inmuebles/crear','InmueblesController@store');

Route::get('/inmobiliaria','AgentesController@index')->name('inmobiliaria');
Route::get('/inmobliliaria/registrar','AgentesController@registrar')->name('registrar');
Route::get('/inmobliliaria/modificar','AgentesController@modificar')->name('modificar');
Route::get('/inmobliliaria/eliminar','AgentesController@eliminar')->name('eliminar');

Route::get('/inmobliliaria/registrarcom','AgentesController@registrarcom')->name('registrarcom');
Route::get('/inmobliliaria/modificarcom','AgentesController@modificarcom')->name('modificarcom');
Route::get('/inmobliliaria/eliminarcom','AgentesController@eliminarcom')->name('eliminarcom');
Route::post('/inmobliliaria/crearcom','AgentesController@store');

Route::get('/chat', 'ChatController@index')->name('chat');
Route::get('/message', 'MessageController@index')->name('message');

Route::resource('Trip_Review', 'Trip_ReviewController');
Route::post('/Trip_Review/Crear','Trip_ReviewController@store');
//Route::post('/Trip_review/store', 'Trip_ReviewController@store')->name("Trip_Review.store");
Route::get('/Trip_Review','Trip_ReviewController@list')->name('Trip_Review.list');
Route::get('/Trip_Review/lista','Trip_ReviewController@liste')->name('Trip_Review.liste');
//Route::get('/Trip_Review/Crear','Trip_ReviewController@create')->name('Trip_Review_Crear');
//Route::get('/Trip_Review/Index','Trip_ReviewController@index')->name('Trip_Review_Index');

Backend/app/Http/Controllers/Trip_ReviewController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;

use App\trip_review;
use App\Http\Bl\Trip_ReviewLogic;
use App\Notifications\TripReviewError;
use App\Notifications\TripReviewFatal;
use App\Notifications\TripReviewWarn;
use App\User;
use Illuminate\Support\Facades\Notification;
use Validator;

class Trip_ReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $trip_review = new Trip_ReviewLogic();
        return $trip_review->ShowLog();
        //$title = 'Trip Review1';
        //$Trip_Review = trip_review::all();

        //return view('Trip_Review.lista', compact('title','Trip_Review'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'comment' => 'required|string|max:255',
            'stars' => 'required|numeric|min:1|max:5',
            'date' => 'required|date',
            'assignment_id_assignment' => 'required|numeric',
        ]);
        //
        if($validator->fails()){
            Notification::route('mail', 'asd@ejemplisho.com')->notify(new TripReviewFatal());
            return response()->json($validator->errors(), 400);

        }

        $trip_review = new Trip_ReviewLogic();
        return $trip_review->StoreTrip($request);
        //

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */


    public function show()
    {
        $trip_review = new Trip_ReviewLogic();
        Notification::route('mail', 'czczyasxczc@ejemplisho.com')->notify(new TripReviewError());
        return $trip_review->ShowLog();
        //$trip_review = trip_review::all();
        //return response()->json($trip_review);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $trip = trip_review::findOrFail($id);

        return view('Trip_Review.edit', compact('trip'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

}

Backend/resources/views/Trip_Review/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Review</title>
</head>
<body>
<h1 class="page-header">Review del recorrido</h1>
</div>
<!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Review
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">
                        <form role="form" method="post" action="{{ url('Trip_Review/Crear')}}">
                            {{ csrf_field() }}


                            <div class="form-group">

                                <label for="validationServer01">Commentario </label>
                                <input type="text" class="form-control is-valid" id="validationServer01" name="comment" placeholder="Comentario" value="" required>
                                <div class="valid-feedback">
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Estrellas</label>
                                <select class="form-control" name="stars">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                </select>
                            </div>


                            <button type="submit" class="btn btn-success">Guardar</button>
                            <button type="reset" class="btn btn-info">Vaciar </button>
</body>
</html>

Backend/resources/views/Trip_Review/edit.blade.php
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Actualizar reviews</h1>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            <br />
        @endif
        <form method="post" action="{{ route('Trip_Review.update', $trip->id_review) }}">
            @method('PATCH')
            @csrf
            <div class="form-group">

                <label for="first_name">id:</label>
                <input type="text" class="form-control" name="id_review" value={{ $trip->id_review }} />
            </div>

            <div class="form-group">
                <label for="last_name">comentario:</label>
                <input type="text" class="form-control" name="comment" value={{ $trip->comment }} />
            </div>

            <div class="form-group">
                <label for="email">estrellas:</label>
                <input type="text" class="form-control" name="stars" value={{ $trip->stars }} />
            </div>
            <div class="form-group">
                <label for="city">fecha:</label>
                <input type="text" class="form-control" name="date" value={{ $trip->date }} />
            </div>
            <div class="form-group">
                <label for="country">id_assignment:</label>
                <input type="text" class="form-control" name="assignment_id_assignment" value={{ $trip->assignment_id_assignment }} />
            </div>

            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>

Backend/resources/views/Trip_Review/index.blade.php
<div class="row">
    <div class="col-sm-12">
        <h1 class="display-3">Contacts</h1>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>Id </th>
                <th>Comment</th>
                <th>stars</th>
                <th>date</th>
                <th>id_assignment</th>
                <th>created</th>
                <th>updated</th>
                <th>deleted</th>
            </tr>
            </thead>
            <tbody>
            @foreach($Trip_Review as $trip)
                <tr>
                    <td>{{ $trip->id_review}}</td>
                    <td>{{ $trip->comment}}</td>
                    <td>{{ $trip->stars}}</td>
                    <td>{{ $trip->date}}</td>
                    <td>{{ $trip->assignment_id_assignment}}</td>
                    <td>{{ $trip->created_at}}</td>
                    <td>{{ $trip->updated_at}}</td>
                    <td>{{ $trip->deleted_at}}</td>


                    <td><a href="{{ url('/Trip_reviewEditar', $trip->id_review) }}" type="button" class="btn btn-outline btn-success">Editar</a></td>

                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $listar->links() }}
    </div>
    <!-- /.table-responsive -->
</div>

Backend/resources/views/Trip_Review/lista.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Trip_Review</title>
</head>
<body>
<h1>Trip_Review</h1>

<div class="flex-center position-ref full-height">
    <div class="top-right links">
        <a href="{{route ('Trip_Review.create')}}">crear</a>
        <a href="{{route ('Trip_Review.liste')}}">lista</a>
    </div>
</div>
<div class="uper">
    @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div><br />
    @endif
    <table class="table table-striped">
        <thead>
        <tr>
            <td>ID</td>
            <td>Book Name</td>
            <td>ISBN Number</td>
            <td>Book Price</td>
            <td colspan="2">Action</td>
        </tr>
        </thead>
        <tbody>
        @foreach($Trip_Review as $trip_review)
            <tr>
                <td>{{$trip_review->id_review}}</td>
                <td>{{$trip_review->comment}}</td>
                <td>{{$trip_review->date}}</td>
                <td>{{$trip_review->assignment_id_assignment}}</td>
            <td><a href="{{route('Trip_Review.edit',$trip_review->id_review)}}" class="btn btn-primary">Editar</a></td>
                <td>

                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <div>
</body>
</html>